/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intefface.frame;


import dao.DaoFactory;
import dao.entities.Group;
import dao.entities.Student;
import dao.entities.Subject;
import intefface.EditGroupForm;
import intefface.AddStudentForm;
import intefface.EditStudentForm;
import intefface.EditSubjectForm;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nastja
 */
public class GroupForm extends javax.swing.JInternalFrame {

    DefaultTableModel modelGroup;
    DefaultTableModel modelStudent;
    DaoFactory daoFactory;
    List<Group> dataTableGroup;
    List<Student> dataTableStudent;
    /**
     * Creates new form GroupEditForm
     */
    public GroupForm() {
        initComponents();
        modelGroup= (DefaultTableModel)tableGroup.getModel();
        daoFactory = DaoFactory.getInstance(DaoFactory.DaoType.ORACLE);
        modelStudent = (DefaultTableModel)tableStudent.getModel();
        fillTableGroup();
        tableGroup.setRowSelectionAllowed(true);
        tableGroup.getSelectionModel().addListSelectionListener(new RowListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGroup = new javax.swing.JTable();
        buttonAddGroup = new javax.swing.JButton();
        buttonEditGroup = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonRefreshGroup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        buttonAddStudent = new javax.swing.JButton();
        buttonEditStud = new javax.swing.JButton();
        buttonDeleteStud = new javax.swing.JButton();
        buttonRefreshStud = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setClosable(true);
        setResizable(true);
        setToolTipText("Group Edit");
        setPreferredSize(new java.awt.Dimension(623, 463));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        tableGroup.setBackground(new java.awt.Color(254, 239, 225));
        tableGroup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group Code"
            }
        ));
        tableGroup.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableGroup);
        tableGroup.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        buttonAddGroup.setBackground(new java.awt.Color(245, 134, 81));
        buttonAddGroup.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        buttonAddGroup.setText("Add");
        buttonAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddGroupActionPerformed(evt);
            }
        });

        buttonEditGroup.setBackground(new java.awt.Color(245, 134, 81));
        buttonEditGroup.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        buttonEditGroup.setText("Edit");
        buttonEditGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditGroupActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(245, 134, 81));
        buttonDelete.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonRefreshGroup.setText("Refresh");
        buttonRefreshGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRefreshGroup)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonAddGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonEditGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRefreshGroup)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddGroup)
                    .addComponent(buttonEditGroup)
                    .addComponent(buttonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        tableStudent.setBackground(new java.awt.Color(254, 239, 225));
        tableStudent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane2.setViewportView(tableStudent);

        buttonAddStudent.setBackground(new java.awt.Color(245, 134, 81));
        buttonAddStudent.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        buttonAddStudent.setText("Add");
        buttonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStudentActionPerformed(evt);
            }
        });

        buttonEditStud.setBackground(new java.awt.Color(245, 134, 81));
        buttonEditStud.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        buttonEditStud.setText("Edit");
        buttonEditStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditStudActionPerformed(evt);
            }
        });

        buttonDeleteStud.setBackground(new java.awt.Color(245, 134, 81));
        buttonDeleteStud.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        buttonDeleteStud.setText("Delete");

        buttonRefreshStud.setText("Refresh");
        buttonRefreshStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshStudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditStud, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDeleteStud))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonRefreshStud)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRefreshStud)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddStudent)
                    .addComponent(buttonEditStud)
                    .addComponent(buttonDeleteStud))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditStudActionPerformed
         int selectedRow = tableStudent.getSelectedRow();
       if(selectedRow != -1){
           Student s = dataTableStudent.get(selectedRow);
           System.out.println(s.getGroupCode());
           EditStudentForm editStudent = new EditStudentForm(dataTableStudent.get(selectedRow));          
           editStudent.setVisible(true);
       }
       else{
           System.out.println("something wrong");
       }
       fillTableStudent();
    }//GEN-LAST:event_buttonEditStudActionPerformed

    private void buttonAddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddGroupActionPerformed
        EditGroupForm addGroupForm = new EditGroupForm();
        addGroupForm.setVisible(true);
        fillTableGroup();
    }//GEN-LAST:event_buttonAddGroupActionPerformed

    private void buttonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStudentActionPerformed
        int selectedRow = tableGroup.getSelectedRow();
       if(selectedRow != -1){
           AddStudentForm addStudent = new AddStudentForm(dataTableGroup.get(selectedRow));          
           addStudent.setVisible(true);
           fillTableStudent();
       }
       
    }//GEN-LAST:event_buttonAddStudentActionPerformed

    private void buttonEditGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditGroupActionPerformed

        int selectedRow = tableGroup.getSelectedRow();
       if(selectedRow != -1){
           EditGroupForm addGroupForm = new EditGroupForm(dataTableGroup.get(selectedRow));
        addGroupForm.setVisible(true);
        fillTableGroup();
       }
       
    }//GEN-LAST:event_buttonEditGroupActionPerformed

    private void buttonRefreshGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshGroupActionPerformed
        
        fillTableGroup();
        System.out.println("new group" + tableGroup.getRowCount());
    }//GEN-LAST:event_buttonRefreshGroupActionPerformed

    private void buttonRefreshStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshStudActionPerformed
     //  clearTableStudent();
       fillTableStudent();
    }//GEN-LAST:event_buttonRefreshStudActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
     int selectedRow = tableGroup.getSelectedRow();
       if(selectedRow != -1){
           System.out.println(dataTableGroup.get(selectedRow));
           daoFactory.createGroupDao().delete(dataTableGroup.get(selectedRow));
       }
       fillTableGroup();
    }//GEN-LAST:event_buttonDeleteActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddGroup;
    private javax.swing.JButton buttonAddStudent;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDeleteStud;
    private javax.swing.JButton buttonEditGroup;
    private javax.swing.JButton buttonEditStud;
    private javax.swing.JButton buttonRefreshGroup;
    private javax.swing.JButton buttonRefreshStud;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableGroup;
    private javax.swing.JTable tableStudent;
    // End of variables declaration//GEN-END:variables

    private void fillTableGroup() {
        clearTableGroup();
        dataTableGroup = daoFactory.createGroupDao().findAll();
   
       for(Group s : dataTableGroup){
           System.out.println(s);
           modelGroup.addRow(new Object[]{s.getGroupCode()});
       }
       
      
    }
    
    public void fillTableStudent(){
        clearTableStudent();
        int groupRow = tableGroup.getSelectedRow();
        if(groupRow != -1){
            Group group = dataTableGroup.get(groupRow);       
            dataTableStudent = daoFactory.createStudentDao().findGroupList(group);
            int i = 0;
            for(Student s : dataTableStudent){
                System.out.println(s);
                modelStudent.addRow(new Object[]{++i, s.getName()});
            }
        }
        
    }

    private void clearTableStudent() {
       int n = tableStudent.getRowCount();
        for (int i = 0; i < n; i++) {
            System.out.println(tableStudent.getRowCount());
          modelStudent.removeRow(0);       
        }
        System.out.println("left " + tableStudent.getRowCount());
        System.out.println("remove colunmn");
        System.out.println("new" + tableStudent.getRowCount());
    }

    private void clearTableGroup() {
        int n = tableGroup.getRowCount();
        for (int i = 0; i < n; i++) {
            System.out.println(tableGroup.getRowCount());
          modelGroup.removeRow(0);       
        }
        System.out.println("left group" + tableGroup.getRowCount());
        System.out.println("remove colunmn");
        System.out.println("new group" + tableGroup.getRowCount());
    }

    private class RowListener implements ListSelectionListener {
     public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            System.out.println("row selected");
            fillTableStudent();
        }
    }
}
