/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intefface;

import intefface.frame.DateAttestationForm;
import intefface.frame.GroupForm;
import intefface.frame.RegistrationForm;
import intefface.frame.SubjectForm;
import intefface.frame.UsersEditForm;

/**
 *
 * @author nastja
 */
public class AdminWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEdit = new javax.swing.JMenu();
        menuItemUserInfo = new javax.swing.JMenuItem();
        menuItemGroupInfo = new javax.swing.JMenuItem();
        menuItemSubjectInfo = new javax.swing.JMenuItem();
        menuDateattestation = new javax.swing.JMenu();
        menuRegistration = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AttestateMe");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(191, 30));

        menuEdit.setText("Edit");

        menuItemUserInfo.setText("User info");
        menuItemUserInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemUserInfoMouseClicked(evt);
            }
        });
        menuItemUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserInfoActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemUserInfo);

        menuItemGroupInfo.setText("Group info");
        menuItemGroupInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemGroupInfoMouseClicked(evt);
            }
        });
        menuItemGroupInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGroupInfoActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemGroupInfo);

        menuItemSubjectInfo.setText("Subject info");
        menuItemSubjectInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemSubjectInfoMouseClicked(evt);
            }
        });
        menuItemSubjectInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSubjectInfoActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemSubjectInfo);

        jMenuBar1.add(menuEdit);

        menuDateattestation.setText("Date attestation");
        menuDateattestation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDateattestationMouseClicked(evt);
            }
        });
        menuDateattestation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDateattestationActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuDateattestation);

        menuRegistration.setText("Registration");
        menuRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrationMouseClicked(evt);
            }
        });
        menuRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrationActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuRegistration);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserInfoActionPerformed
       System.out.println("uerRegistr");
       UsersEditForm usersEditForm = new UsersEditForm();
        desktop.add(usersEditForm);
        usersEditForm.setVisible(true);
    }//GEN-LAST:event_menuItemUserInfoActionPerformed

    private void menuItemGroupInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGroupInfoActionPerformed
        GroupForm groupEditForm = new GroupForm();
        desktop.add(groupEditForm);
        groupEditForm.setVisible(true);
    }//GEN-LAST:event_menuItemGroupInfoActionPerformed

    private void menuItemUserInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemUserInfoMouseClicked
        System.out.println("uerRegistr");
        
    }//GEN-LAST:event_menuItemUserInfoMouseClicked

    private void menuRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrationActionPerformed
        System.out.println("clickRegistr");
       
    }//GEN-LAST:event_menuRegistrationActionPerformed

    private void menuDateattestationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDateattestationActionPerformed
        System.out.println("date");
    }//GEN-LAST:event_menuDateattestationActionPerformed

    private void menuRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrationMouseClicked
      System.out.println("clickRegistr");
       RegistrationForm registrationForm = new RegistrationForm();
        desktop.add(registrationForm);
        registrationForm.setVisible(true);
    }//GEN-LAST:event_menuRegistrationMouseClicked

    private void menuDateattestationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDateattestationMouseClicked
        DateAttestationForm dateAttestationForm = new DateAttestationForm();
        desktop.add(dateAttestationForm);
        dateAttestationForm.setVisible(true);
    }//GEN-LAST:event_menuDateattestationMouseClicked

    private void menuItemGroupInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemGroupInfoMouseClicked
      
    }//GEN-LAST:event_menuItemGroupInfoMouseClicked

    private void menuItemSubjectInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemSubjectInfoMouseClicked
        
    }//GEN-LAST:event_menuItemSubjectInfoMouseClicked

    private void menuItemSubjectInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSubjectInfoActionPerformed
       SubjectForm subjectForm = new SubjectForm();
        desktop.add(subjectForm);
        subjectForm.setVisible(true);
    }//GEN-LAST:event_menuItemSubjectInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDateattestation;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuItemGroupInfo;
    private javax.swing.JMenuItem menuItemSubjectInfo;
    private javax.swing.JMenuItem menuItemUserInfo;
    private javax.swing.JMenu menuRegistration;
    // End of variables declaration//GEN-END:variables
}
