/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intefface;

import dao.DaoFactory;
import dao.entities.Group;
import dao.entities.User;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import validators.CheckInput;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import validators.JTextFieldLimit;



/**
 *
 * @author nastja
 */
public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    DaoFactory daoFactory;
    private Component frame;
    List<Group> groups;
    
    public MainWindow() {
        initComponents();
       daoFactory = DaoFactory.getInstance(DaoFactory.DaoType.ORACLE);
       
       groups = daoFactory.createGroupDao().findAll();
       
       textFieldLogin.setDocument(new JTextFieldLimit(15));
       passwordField.setDocument(new JTextFieldLimit(15));
       fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogIn = new javax.swing.JPanel();
        textFieldLogin = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        buttonLogIn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        labelWrongData = new javax.swing.JLabel();
        labelWrongLogin = new javax.swing.JLabel();
        labelWrongPass = new javax.swing.JLabel();
        ViewAttestation = new javax.swing.JPanel();
        comboBoxGroupCode = new javax.swing.JComboBox();
        labelEnterGroupCode = new javax.swing.JLabel();
        labelViewAttestList = new javax.swing.JLabel();
        buttonView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AttestateMe");
        setBackground(new java.awt.Color(255, 204, 153));
        setName("AttestateMe"); // NOI18N

        textFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoginActionPerformed(evt);
            }
        });
        textFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldLoginKeyTyped(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelLogin.setText("Enter login:");

        labelPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelPassword.setText("Enter password:");

        buttonLogIn.setBackground(new java.awt.Color(245, 134, 81));
        buttonLogIn.setFont(buttonLogIn.getFont().deriveFont(buttonLogIn.getFont().getStyle() | java.awt.Font.BOLD));
        buttonLogIn.setText("Log In");
        buttonLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogInMouseClicked(evt);
            }
        });
        buttonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogInActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        labelWrongData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelWrongData.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panelLogInLayout = new javax.swing.GroupLayout(panelLogIn);
        panelLogIn.setLayout(panelLogInLayout);
        panelLogInLayout.setHorizontalGroup(
            panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogInLayout.createSequentialGroup()
                        .addComponent(buttonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelWrongData, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLogInLayout.createSequentialGroup()
                        .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLogInLayout.createSequentialGroup()
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(labelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLogInLayout.createSequentialGroup()
                                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogInLayout.createSequentialGroup()
                                .addComponent(labelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelWrongLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLogInLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(150, Short.MAX_VALUE)))
        );
        panelLogInLayout.setVerticalGroup(
            panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogInLayout.createSequentialGroup()
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLogInLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labelWrongLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogInLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogInLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelWrongData, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogInLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(buttonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLogInLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        ViewAttestation.setBackground(new java.awt.Color(255, 204, 102));

        comboBoxGroupCode.setBackground(new java.awt.Color(245, 134, 81));
        comboBoxGroupCode.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        comboBoxGroupCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGroupCodeActionPerformed(evt);
            }
        });

        labelEnterGroupCode.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelEnterGroupCode.setText("Enter group's code:");

        labelViewAttestList.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        labelViewAttestList.setForeground(new java.awt.Color(51, 0, 0));
        labelViewAttestList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewAttestList.setText("View attetation list");

        buttonView.setBackground(new java.awt.Color(245, 134, 81));
        buttonView.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewAttestationLayout = new javax.swing.GroupLayout(ViewAttestation);
        ViewAttestation.setLayout(ViewAttestationLayout);
        ViewAttestationLayout.setHorizontalGroup(
            ViewAttestationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAttestationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnterGroupCode, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(comboBoxGroupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(ViewAttestationLayout.createSequentialGroup()
                .addGroup(ViewAttestationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewAttestationLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(labelViewAttestList, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewAttestationLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(buttonView, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewAttestationLayout.setVerticalGroup(
            ViewAttestationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAttestationLayout.createSequentialGroup()
                .addComponent(labelViewAttestList, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(ViewAttestationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnterGroupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxGroupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ViewAttestation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewAttestation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogInActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void buttonLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogInMouseClicked
        String login = textFieldLogin.getText();
        char[] password = passwordField.getPassword();
        labelWrongLogin.setVisible(false);
        labelWrongPass.setVisible(false);
        labelWrongData.setVisible(false);
        
        System.out.println("buttonclick");
        System.out.println(login);
        
        if(checkInputData( password, login)){
          /*if(adminCheck(login, password)){
              System.out.println("admin");
              AdminWindow adminWindow = new AdminWindow();
              adminWindow.setVisible(true);
              this.setVisible(false);
             
              
              System.out.println("admin");
          }else if(userCheck(login, password)){
              
          } else {
              labelWrongData.setVisible(true);
              labelWrongData.setText("Wrong data.Try again");
             // textFieldLogin.
          }*/
            System.out.println("valid");
           User user =  daoFactory.createUserDao().find(new String(password), login);
            checkUser(user);
        }
    }//GEN-LAST:event_buttonLogInMouseClicked

    private void checkUser(User user) {
        if(user.isAdmin()){
            System.out.println("admin");
            AdminWindow adminWindow = new AdminWindow();
            adminWindow.setVisible(true);
            this.setVisible(false);
        }
        else if(!user.isEmpty()){
            UserWindow userWindow = new UserWindow(user);
            userWindow.setVisible(true);
        }
        else{
            labelWrongData.setVisible(true);
            labelWrongData.setText("Wrong login or password");
        }
    }

    private boolean checkInputData(char[] password, String login) {
        CheckInput checkInput = new CheckInput();
        if(checkInput.checkPassword(password) && checkInput.checkLogin(login)){
            return true;
        }else{
        if(!checkInput.checkPassword(password)){
            System.out.println("Wrong password");
            labelWrongPass.setVisible(true);
            labelWrongPass.setText("Wrong password");
        }
        if(!checkInput.checkLogin(login)){
            System.out.println("Wrong login");
            labelWrongLogin.setVisible(true);
            labelWrongLogin.setText("Wrong login");
        }
        return false;
        }
    }

    private void comboBoxGroupCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGroupCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxGroupCodeActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
         AttestationListWindow alw = new AttestationListWindow((Group) comboBoxGroupCode.getSelectedItem());
         alw.setVisible(true);
    }//GEN-LAST:event_buttonViewActionPerformed

    private void textFieldLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldLoginKeyTyped
        
    }//GEN-LAST:event_textFieldLoginKeyTyped

    private void textFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewAttestation;
    private javax.swing.JButton buttonLogIn;
    private javax.swing.JButton buttonView;
    private javax.swing.JComboBox comboBoxGroupCode;
    private javax.swing.JLabel labelEnterGroupCode;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelViewAttestList;
    private javax.swing.JLabel labelWrongData;
    private javax.swing.JLabel labelWrongLogin;
    private javax.swing.JLabel labelWrongPass;
    private javax.swing.JPanel panelLogIn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldLogin;
    // End of variables declaration//GEN-END:variables

 

    private void fillComboBox() {
        
        for(Group g: groups){
            comboBoxGroupCode.addItem(g);
        }
    }
}
